### ISSUE TITLE
amazonica.aws.sqs/create-queue not finding credentials set with `defcredential`

### ISSUE THREAD

**Issue by gws** [mcohen01/amazonica#108]
When I use `defcredential`:

```clojure
(defcredential "my-access-key-id" "my-secret-key" "my-region")
(amazonica.aws.sqs/create-queue :queue-name "foo" :attributes {:VisibilityTimeout 30})
```

that results in

```
Caused by: com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
        at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2330)
        at com.amazonaws.services.sqs.AmazonSQSClient.createQueue(AmazonSQSClient.java:1270)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at amazonica.core$fn_call$fn__2054.invoke(core.clj:752)
        at amazonica.core$intern_function$fn__2073.doInvoke(core.clj:803)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:624)
        at amazonica.aws.sqs$attr_keys__GT_str.doInvoke(sqs.clj:20)
        at clojure.lang.RestFn.invoke(RestFn.java:490)
        at clojure.lang.Var.invoke(Var.java:401)
        at clojure.lang.AFn.applyToHelper(AFn.java:171)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.core$apply.invoke(core.clj:626)
        at robert.hooke$compose_hooks$fn__7352.doInvoke(hooke.clj:40)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:624)
        at robert.hooke$run_hooks.invoke(hooke.clj:46)
        at robert.hooke$prepare_for_hooks$fn__7357$fn__7358.doInvoke(hooke.clj:54)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        ... snipped ...
```

The `defcredential` method seems to work fine when talking to DynamoDB and S3.

I **do not** have credentials specified anywhere else - no profile, environment variables, instance metadata, etc which is probably related.

I'm using version **0.3.10**.

I'm happy to provide more information to help reproduce the issue. Thanks!

**Comment by mcohen01** [comment]
Sorry about that. There are too many ways to handle auth in the library at this point. defcredential was probably a mistake, but i've been reluctant to remove it in order to preserve back compat. In any case, 0.3.11 should work for you.

**Comment by gws** [comment]
Thank you! I hadn't realized `defcredential` was "deprecated," and I was just using it to get started anyway. I'm in the process of migrating things to use explicit credential maps. I appreciate the quick response and fix, though.
