### ISSUE TITLE
Expected authority at index 8: https://

### ISSUE THREAD

**Issue by d11wtq** [mcohen01/amazonica#109]
I'm just getting started with amazonica for CloudFormation Stack maintenance and trying a simple call just to sanity check it's all working. I know this won't output anything, I just want to see it run without crashing:

``` clojure
(ns stack.core
  (:require [amazonica.aws.cloudformation :as cloudformation]))

(defn -main
  "Application entry point."
  [& args]
  (cloudformation/describe-stacks))
```

This throws a `java.net.URISyntaxException`. I've tried other API calls too and get the same Exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: java.net.URISyntaxException: Expected authority at index 8: https://, compiling:(/tmp/form-init8540412197008474799.clj:1:72)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: java.net.URISyntaxException: Expected authority at index 8: https://
	at com.amazonaws.AmazonWebServiceClient.toURI(AmazonWebServiceClient.java:182)
	at com.amazonaws.AmazonWebServiceClient.setEndpoint(AmazonWebServiceClient.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at amazonica.core$amazon_client_STAR_.invoke(core.clj:227)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$memoize$fn__5097.doInvoke(core.clj:5846)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at amazonica.core$candidate_client.invoke(core.clj:736)
	at amazonica.core$fn_call$fn__348.invoke(core.clj:746)
	at clojure.lang.Delay.deref(Delay.java:37)
	at clojure.core$deref.invoke(core.clj:2200)
	at amazonica.core$fn_call$fn__350.invoke(core.clj:749)
	at amazonica.core$intern_function$fn__369.doInvoke(core.clj:802)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at stack.core$_main.doInvoke(core.clj:9)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invoke(form-init8540412197008474799.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 11 more
Caused by: java.net.URISyntaxException: Expected authority at index 8: https://
	at java.net.URI$Parser.fail(URI.java:2825)
	at java.net.URI$Parser.failExpecting(URI.java:2831)
	at java.net.URI$Parser.parseHierarchical(URI.java:3079)
	at java.net.URI$Parser.parse(URI.java:3030)
	at java.net.URI.<init>(URI.java:595)
	at com.amazonaws.AmazonWebServiceClient.toURI(AmazonWebServiceClient.java:180)
	... 38 more
```

Using Clojure 1.6.0 via Leiningen and Amazonica 0.3.12.

**Comment by mcohen01** [comment]
The Java SDK is picking up your credentials from somewhere, see [here](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) for the list of locations searched, probably a credentials file at `~/.aws/credentials`. Do you have a region configured somewhere beginning with https://? I think the region endpoint needs to be of the form e.g. "us-east-1" or something like "dynamodb.us-west-2.amazonaws.com". Protocol is specified separately I think.

**Comment by d11wtq** [comment]
```
$ ls ~/.aws
ls: cannot access /home/default/.aws: No such file or directory
```

```
AWS_DEFAULT_REGION=
AWS_SECRET_ACCESS_KEY=<masked>
AWS_REGION=ap-southeast-2
AWS_ACCESS_KEY_ID=<masked>
AWS_SECRET_KEY=<masked>
```

I've unset the blank `$AWS_DEFAULT_REGION` and the problem has gone away. Thanks for the pointers :)
