### ISSUE TITLE
Can't get object-metadata

### ISSUE THREAD

**Issue by chenfisher** [mcohen01/amazonica#138]
When trying to get object metadata from download object I get the following error:
```
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at amazonica.core$get_fields$iter__2085__2089$fn__2090$fn__2091.invoke(core.clj:606)
	at amazonica.core$get_fields$iter__2085__2089$fn__2090.invoke(core.clj:605)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30)
	at clojure.core.protocols$fn__6078.invoke(protocols.clj:54)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at clojure.core$into.invoke(core.clj:6341)
	at amazonica.core$get_fields.invoke(core.clj:605)
	at amazonica.core$eval2101$fn__2102.invoke(core.clj:643)
	at amazonica.core$eval2056$fn__2057$G__2047__2062.invoke(core.clj:560)
	at amazonica.aws.s3transfer$eval2259$fn__2260$fn__2265.invoke(s3transfer.clj:64)
	at user$eval18683$listener__18684.invoke(form-init4924955418979348527.clj:5)
	at amazonica.aws.s3transfer$add_listener$fn$reify__2209.progressChanged(s3transfer.clj:24)
	at com.amazonaws.event.ProgressListenerChain.progressChanged(ProgressListenerChain.java:98)
	at com.amazonaws.event.SDKProgressPublisher$1.run(SDKProgressPublisher.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

Using exactly as in the docs:
```
(let [dl  (download bucket
                    file
                    down-dir)
      listener #(if (= :completed (:event %))
                    (println ((:object-metadata dl)))
                    (println %))]
  ((:add-progress-listener dl) listener))
```

Using: ```[amazonica "0.3.22"]```

Thanks for your help

**Comment by chenfisher** [comment]
Thanks for the quick fix!
