### ISSUE TITLE
Client configuration throwing exception : java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by marcvincenti** [mcohen01/amazonica#248]
Hello, i was using [amazonica "0.3.67"] and i want to update amazonica to "0.3.79".

However, when i use a version >0.69 (coresponding to the Java SDK upgrade to 1.11.20) I get the following error : 

> Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z, compiling:(core.clj:209:1)

Here is the stacktrace : 
```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDefaultDeserializer(BasicDeserializerFactory.java:1529)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.findStdDeserializer(BeanDeserializerFactory.java:167)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:132)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3838)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3732)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2679)
	at com.amazonaws.internal.config.InternalConfig.loadfrom(InternalConfig.java:236)
	at com.amazonaws.internal.config.InternalConfig.load(InternalConfig.java:249)
	at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:304)
	at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:141)
	at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:136)
	at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:97)
	at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:60)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at amazonica.core$get_client_configuration.<clinit>(core.clj:209)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at clojure.lang.Compiler$ObjExpr.eval(Compiler.java:4913)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:451)
	... 127 more
Subprocess failed
```
Is it because of my poject ? Other dependencies ?

**Comment by mcohen01** [comment]
Jackson is a constant source of dependency conflicts, particularly with amazonica. I would look through the output of `lein deps :tree` and see if there's any obvious candidates for exclusion.

**Comment by marcvincenti** [comment]
I haven't found a gound candidate for exclusion but i saw the conflict was with ring-json and i updated ring-json to the latest version. Thank you.
