### ISSUE TITLE
AWS Polly throws "Could not initialize class com.amazonaws.http.AmazonHttpClient"

### ISSUE THREAD

**Issue by dviramontes** [mcohen01/amazonica#294]
Hello, i'm getting this exception:
`Could not initialize class com.amazonaws.http.AmazonHttpClient`

when I try to use:
```
  (polly/synthesize-speech
      :Text "Tesla Passes Ford by Market Cap Before Musk Delivers Model 3"
      :OutputFormat "mp3"
      :VoiceId "Ivy")
```

wondering if anyone has seen this before ?
I have my credentials in `~/.aws/credentials` and I also tried wrapping the `polly` call
in the `with-credentials` macro but no luck.

**Comment by mcohen01** [comment]
```clj
(polly/synthesize-speech
      :text "Tesla Passes Ford by Market Cap Before Musk Delivers Model 3"
      :output-format "mp3"
      :voice-id "Ivy")
```

**Comment by dviramontes** [comment]
@mcohen01 just tried ^ 
same outcome... :/

**Comment by mcohen01** [comment]
can you post the full stacktrace along with version of amz, jdk, and clojure?

**Comment by dviramontes** [comment]
of course

- __amazonica version:__
`[amazonica "0.3.94"]`

- __JDK__
```
➜  api git:(feat-aws-polly) ✗ java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```
- __stack trace__
```
Mon Apr 03 14:36:06 MDT 2017 [worker-4] ERROR - POST /api/aws/text2speech
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.http.AmazonHttpClient
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:163)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:154)
	at com.amazonaws.services.polly.AmazonPollyClient.<init>(AmazonPollyClient.java:264)
	at com.amazonaws.services.polly.AmazonPollyClient.<init>(AmazonPollyClient.java:239)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:180)
	at amazonica.core$invoke_constructor.invokeStatic(core.clj:50)
	at amazonica.core$invoke_constructor.invoke(core.clj:48)
	at amazonica.core$create_client.invokeStatic(core.clj:165)
	at amazonica.core$create_client.invoke(core.clj:154)
	at amazonica.core$amazon_client_STAR_.invokeStatic(core.clj:264)
	at amazonica.core$amazon_client_STAR_.invoke(core.clj:260)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$memoize$fn__5708.doInvoke(core.clj:6107)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at amazonica.core$candidate_client$fn__20559.invoke(core.clj:839)
	at clojure.lang.Delay.deref(Delay.java:37)
	at clojure.core$deref.invokeStatic(core.clj:2228)
	at clojure.core$deref.invoke(core.clj:2214)
	at amazonica.core$candidate_client.invokeStatic(core.clj:840)
	at amazonica.core$candidate_client.invoke(core.clj:823)
	at amazonica.core$fn_call$fn__20567.invoke(core.clj:853)
	at clojure.lang.Delay.deref(Delay.java:37)
	at clojure.core$deref.invokeStatic(core.clj:2228)
	at clojure.core$deref.invoke(core.clj:2214)
	at amazonica.core$fn_call$fn__20569.invoke(core.clj:856)
	at amazonica.core$intern_function$fn__20597.doInvoke(core.clj:929)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at mmmanyfold.routes.aws.polly$handle_text_2_speech.invokeStatic(polly.clj:13)
	at mmmanyfold.routes.aws.polly$handle_text_2_speech.invoke(polly.clj:12)
	at compojure.response$eval442$fn__443.invoke(response.clj:33)
	at compojure.response$eval397$fn__398$G__388__405.invoke(response.clj:6)
	at compojure.core$make_route$fn__2072.invoke(core.clj:135)
	at compojure.core$wrap_route_middleware$fn__2065.invoke(core.clj:122)
	at compojure.core$wrap_route_info$fn__2069.invoke(core.clj:126)
	at compojure.core$if_route$fn__2023.invoke(core.clj:45)
	at compojure.core$if_method$fn__2013.invoke(core.clj:27)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__2079.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__2083.invoke(core.clj:156)
	at compojure.core$routing$fn__2079.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at mmmanyfold.routes.aws.polly$fn__23151.invokeStatic(polly.clj:20)
	at mmmanyfold.routes.aws.polly$fn__23151.invoke(polly.clj:20)
	at compojure.core$if_context$fn__2141.invoke(core.clj:220)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__11184.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__2079.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__2083.invoke(core.clj:156)
	at compojure.core$routing$fn__2079.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at mmmanyfold.api$fn__23202.invokeStatic(api.clj:14)
	at mmmanyfold.api$fn__23202.invoke(api.clj:14)
	at compojure.core$if_context$fn__2141.invoke(core.clj:220)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__2079.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__2083.invoke(core.clj:156)
	at clojure.lang.Var.invoke(Var.java:379)
	at compojure.core$routing$fn__2079.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__2083.invoke(core.clj:156)
	at clojure.lang.Var.invoke(Var.java:379)
	at ring.middleware.reload$wrap_reload$fn__25316.invoke(reload.clj:38)
	at selmer.middleware$wrap_error_page$fn__25329.invoke(middleware.clj:9)
	at prone.middleware$wrap_exceptions$fn__25527.invoke(middleware.clj:126)
	at ring.middleware.json$wrap_json_response$fn__25930.invoke(json.clj:87)
	at ring.middleware.format_params$wrap_format_params$fn__5070.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__5070.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__5070.invoke(format_params.clj:119)
	at ring.middleware.format_response$wrap_format_response$fn__5833.invoke(format_response.clj:183)
	at mmmanyfold.middleware$wrap_formats$fn__26461.invoke(middleware.clj:17)
	at ring.middleware.flash$wrap_flash$fn__26005.invoke(flash.clj:35)
	at ring.middleware.session$wrap_session$fn__26179.invoke(session.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__5967.invoke(keyword_params.clj:35)
	at ring.middleware.nested_params$wrap_nested_params$fn__6019.invoke(nested_params.clj:86)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__26299.invoke(multipart_params.clj:133)
	at ring.middleware.params$wrap_params$fn__6109.invoke(params.clj:64)
	at ring.middleware.cookies$wrap_cookies$fn__26126.invoke(cookies.clj:161)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__26393.invoke(absolute_redirects.clj:38)
	at ring.middleware.resource$wrap_resource$fn__26321.invoke(resource.clj:28)
	at ring.middleware.content_type$wrap_content_type$fn__11288.invoke(content_type.clj:30)
	at ring.middleware.default_charset$wrap_default_charset$fn__26368.invoke(default_charset.clj:26)
	at ring.middleware.not_modified$wrap_not_modified$fn__11317.invoke(not_modified.clj:52)
	at ring.middleware.x_headers$wrap_xss_protection$fn__25981.invoke(x_headers.clj:71)
	at ring.middleware.x_headers$wrap_frame_options$fn__25969.invoke(x_headers.clj:38)
	at ring.middleware.x_headers$wrap_content_type_options$fn__25975.invoke(x_headers.clj:53)
	at ring.middleware.cors$wrap_cors$fn__25741.invoke(cors.clj:156)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mcohen01** [comment]
hmmm....what do the deps look like in your project.clj? are you excluding anything from AWS?

**Comment by dviramontes** [comment]
Hi, these are my [dependencies](https://github.com/mmmanyfold/api/blob/feat-aws-polly/project.clj), not excluding anything right now.

**Comment by mcohen01** [comment]
`[clj-facebook-graph "0.4.0" :exclusions [clj-http]]` fixes things for me

**Comment by mcohen01** [comment]
not sure how that will affect `clj-facebook-graph` api though....

**Comment by dviramontes** [comment]
@mcohen01 that totally worked! 🎉 
And my facebook-graph endpoint looks intact 👍 
Thank you so much, closing this.

**Comment by mcohen01** [comment]
👍
