### ISSUE TITLE
NumberFormatException For input string: "227321477026750700000"  java.lang.NumberFormatException.forInputString (NumberFormatException.java:65)

### ISSUE THREAD

**Issue by vpamarnath** [mcohen01/amazonica#420]
Amazonica version 0.3.143.

When entering a number larger than ```Long/MAX_LONG``` at the frontend, amazonica writes it to the underlying dynamodb.

When reading it back, the exception (also pasted in the title) __NumberFormatException For input string: "227321477026750700000"  java.lang.NumberFormatException.forInputString (NumberFormatException.java:65)__ is thrown.  The number in question is also quoted in the exception.

Any work around for this will be greatly appreciated.

Stack trace below:

```
java.lang.NumberFormatException: For input string: "333489926649892600000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_222]
	at java.lang.Long.parseLong(Long.java:592) ~[na:1.8.0_222]
	at java.lang.Long.parseLong(Long.java:631) ~[na:1.8.0_222]
	at amazonica.aws.dynamodbv2$parse_number.invokeStatic(dynamodbv2.clj:20) ~[na:na]
	at amazonica.aws.dynamodbv2$parse_number.invoke(dynamodbv2.clj:16) ~[na:na]
	at amazonica.aws.dynamodbv2$eval53103$fn__53104.invoke(dynamodbv2.clj:29) ~[na:na]
	at amazonica.core$eval52917$fn__52918$G__52908__52923.invoke(core.clj:659) ~[na:na]
	at amazonica.aws.dynamodbv2$eval53103$fn__53104$fn__53112.invoke(dynamodbv2.clj:32) ~[na:na]
	at clojure.core$map$fn__5587.invoke(core.clj:2747) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RT.seq(RT.java:528) ~[clojure-1.9.0.jar:na]
	at clojure.core$seq__5124.invokeStatic(core.clj:137) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invokeStatic(core.clj:6815) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invoke(core.clj:6807) ~[clojure-1.9.0.jar:na]
	at amazonica.aws.dynamodbv2$eval53103$fn__53104.invoke(dynamodbv2.clj:32) ~[na:na]
	at amazonica.core$eval52917$fn__52918$G__52908__52923.invoke(core.clj:659) ~[na:na]
	at amazonica.aws.dynamodbv2$eval53103$fn__53104$fn__53112.invoke(dynamodbv2.clj:32) ~[na:na]
	at clojure.core$map$fn__5587.invoke(core.clj:2745) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:na]
	at clojure.lang.Cons.next(Cons.java:39) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RT.next(RT.java:706) ~[clojure-1.9.0.jar:na]
	at clojure.core$next__5108.invokeStatic(core.clj:64) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7852.invokeStatic(protocols.clj:169) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7852.invoke(protocols.clj:124) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7807$G__7802__7816.invoke(protocols.clj:19) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invokeStatic(core.clj:6815) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invoke(core.clj:6807) ~[clojure-1.9.0.jar:na]
	at amazonica.aws.dynamodbv2$eval53103$fn__53104.invoke(dynamodbv2.clj:32) ~[na:na]
	at amazonica.core$eval52917$fn__52918$G__52908__52923.invoke(core.clj:659) ~[na:na]
	at amazonica.aws.dynamodbv2$eval53103$fn__53104$fn__53112.invoke(dynamodbv2.clj:32) ~[na:na]
	at clojure.core$map$fn__5587.invoke(core.clj:2745) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:na]
	at clojure.lang.Cons.next(Cons.java:39) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RT.next(RT.java:706) ~[clojure-1.9.0.jar:na]
	at clojure.core$next__5108.invokeStatic(core.clj:64) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7852.invokeStatic(protocols.clj:169) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7852.invoke(protocols.clj:124) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7807$G__7802__7816.invoke(protocols.clj:19) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invokeStatic(core.clj:6815) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invoke(core.clj:6807) ~[clojure-1.9.0.jar:na]
	at amazonica.aws.dynamodbv2$eval53103$fn__53104.invoke(dynamodbv2.clj:32) ~[na:na]
	at amazonica.core$eval52917$fn__52918$G__52908__52923.invoke(core.clj:659) ~[na:na]
	at clojure.core$map$fn__5587.invoke(core.clj:2747) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RT.seq(RT.java:528) ~[clojure-1.9.0.jar:na]
	at clojure.core$seq__5124.invokeStatic(core.clj:137) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invokeStatic(core.clj:6815) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invoke(core.clj:6807) ~[clojure-1.9.0.jar:na]
	at amazonica.aws.dynamodbv2$eval53103$fn__53104.invoke(dynamodbv2.clj:31) ~[na:na]
	at amazonica.core$eval52917$fn__52918$G__52908__52923.invoke(core.clj:659) ~[na:na]
	at clojure.core$map$fn__5587.invoke(core.clj:2745) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RT.seq(RT.java:528) ~[clojure-1.9.0.jar:na]
	at clojure.core$seq__5124.invokeStatic(core.clj:137) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invokeStatic(core.clj:6815) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invoke(core.clj:6807) ~[clojure-1.9.0.jar:na]
	at clojure.algo.generic.functor$eval52671$fn__52672.invoke(functor.clj:31) ~[na:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[clojure-1.9.0.jar:na]
	at amazonica.core$eval52965$fn__52966.invoke(core.clj:725) ~[na:na]
	at amazonica.core$eval52917$fn__52918$G__52908__52923.invoke(core.clj:659) ~[na:na]
	at clojure.core$map$fn__5587.invoke(core.clj:2745) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RT.seq(RT.java:528) ~[clojure-1.9.0.jar:na]
	at clojure.core$seq__5124.invokeStatic(core.clj:137) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invokeStatic(core.clj:6815) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invoke(core.clj:6807) ~[clojure-1.9.0.jar:na]
	at clojure.algo.generic.functor$eval52671$fn__52672.invoke(functor.clj:31) ~[na:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[clojure-1.9.0.jar:na]
	at amazonica.core$eval52971$fn__52972.invoke(core.clj:732) ~[na:na]
	at amazonica.core$eval52917$fn__52918$G__52908__52923.invoke(core.clj:659) ~[na:na]
	at amazonica.core$get_fields$iter__52945__52949$fn__52950$fn__52951.invoke(core.clj:708) ~[na:na]
	at amazonica.core$get_fields$iter__52945__52949$fn__52950.invoke(core.clj:707) ~[na:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RT.seq(RT.java:528) ~[clojure-1.9.0.jar:na]
	at clojure.core$seq__5124.invokeStatic(core.clj:137) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invokeStatic(core.clj:6815) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invoke(core.clj:6807) ~[clojure-1.9.0.jar:na]
	at amazonica.core$get_fields.invokeStatic(core.clj:706) ~[na:na]
	at amazonica.core$get_fields.invoke(core.clj:701) ~[na:na]
	at amazonica.core$eval52983$fn__52984.invoke(core.clj:745) ~[na:na]
	at amazonica.core$eval52917$fn__52918$G__52908__52923.invoke(core.clj:659) ~[na:na]
	at amazonica.core$fn_call$fn__53029.invoke(core.clj:877) ~[na:na]
	at amazonica.core$intern_function$fn__53069.doInvoke(core.clj:1032) ~[na:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:657) [clojure-1.9.0.jar:na]
	at clojure.core$apply.invoke(core.clj:652) [clojure-1.9.0.jar:na]
```

**Comment by mcohen01** [comment]
Validate your data with `Long/parseLong` before you send it to dynamo?

**Comment by mcohen01** [comment]
`0.3.145` is on clojars
