### ISSUE TITLE
AWS v1 SDK EOL December 31 2025

### ISSUE THREAD

**Issue by dharrigan** [mcohen01/amazonica#481]
Hi,

With the latest updates to the AWS dependencies, a new warning is now being displayed when compiling an application that uses Amazonica:

```
2024-08-09T15:16:31.592Z WARN [com.amazonaws.util.VersionInfoUtils:85] - The AWS SDK for Java 1.x entered maintenance mode starting July 31, 2024 and will reach end of support on December 31, 2025. For more information, see https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-1-x-is-in-maintenance-mode-effective-july-31-2024/
You can print where on the file system the AWS SDK for Java 1.x core runtime is located by setting the AWS_JAVA_V1_PRINT_LOCATION environment variable or aws.java.v1.printLocation system property to 'true'.
This message can be disabled by setting the AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT environment variable or aws.java.v1.disableDeprecationAnnouncement system property to 'true'.
The AWS SDK for Java 1.x is being used here:
at java.base/java.lang.Thread.getStackTrace(Thread.java:2418)
at com.amazonaws.util.VersionInfoUtils.printDeprecationAnnouncement(VersionInfoUtils.java:81)
at com.amazonaws.util.VersionInfoUtils.<clinit>(VersionInfoUtils.java:59)
at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:94)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:529)
at java.base/java.lang.Class.forName(Class.java:508)
at clojure.lang.RT.classForName(RT.java:2209)
at clojure.lang.RT.classForName(RT.java:2218)
at amazonica.core$get_client_configuration.<clinit>(core.clj:247)
```

There is over a year until the library becomes unsupported, so hopefully there is a chance that Amazonica can migrate to Version 2 of the AWS libraries eventually.

For the moment, we are setting the environment variable, as suggested, to mask this warning.

Thank you.

-=david=-

**Comment by IgorAnghelcev** [comment]
how you disable whit warn?

**Comment by IgorAnghelcev** [comment]
i write in env but warn not going anywhere

aws:
  java:
    v1:
      disableDeprecationAnnouncement: false

**Comment by dharrigan** [comment]
Hi,

Put this into your script file (or whatever) that launches your program:

```
export AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT="true"
```

**Comment by asubbpr** [comment]
Are there any plans to migrate to the SDK v2.x? Is it even possible?
